### ISSUE TITLE
On-screen keyboard

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/senmai-mss#2]
Looks the same as the one on Fihrist.

**Comment by IgnatG** [comment]
Yup - I don;t have additional languages for it.

**Comment by IgnatG** [comment]
Cool. I've updated that now - it defaults to Burmese. & I've pushed it to develop

**Comment by andrew-morrison** [comment]
It has been requested that the on-screen keyboard be removed entirely for Senmai.

**Comment by IgnatG** [comment]
//sorted - I took it out
